### ISSUE TITLE
Error after cloudflare change of technique

### ISSUE THREAD

**Issue by gaardiolor** [pavlodvornikov/aiocfscrape#11]
Apparently cloudflare changed something today, see https://github.com/Anorov/cloudflare-scrape/issues/193 . Already fixed cfscrape, but aiocfscrape continues to give an error.

```
Traceback (most recent call last):
  File "/usr/local/scripts/test/test.py", line 459, in wrapper
    result = json.loads(json.dumps(await action(*args, **kwargs)), parse_int=d, parse_float=d)
  File "/usr/local/scripts/test/site.py", line 73, in prepare
    success = await self.test_cookies()
  File "/usr/local/scripts/test/site.py", line 121, in test_cookies
    await self.aiohttp_session.get(site, proxy=self.aiohttp_proxy)
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/aiocfscrape/__init__.py", line 36, in _request
    return await self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/aiocfscrape/__init__.py", line 87, in solve_cf_challenge
    params["jschl_answer"] = str(float(js2py.eval_js(js)) + len(domain))
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/js2py/evaljs.py", line 113, in eval_js
    return e.eval(js)
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/js2py/evaljs.py", line 182, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/js2py/evaljs.py", line 177, in execute
    exec(compiled, self._context)
  File "<EvalJS snippet>", line 4, in <module>
  File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/js2py/base.py", line 899, in __call__
    return self.call(self.GlobalObject, args)
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/js2py/base.py", line 1344, in call
    return Js(self.code(*args))
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/js2py/host/jseval.py", line 16, in Eval
    py_code = translate_js(code.to_string().value, '')
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/js2py/translators/translator.py", line 66, in translate_js
    parsed = parser.parse(js) # js to esprima syntax tree
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 2863, in parse
    program = self.parseProgram();
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 2834, in parseProgram
    body = self.parseScriptBody()
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 2823, in parseScriptBody
    statement = self.parseStatementListItem();
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1989, in parseStatementListItem
    return self.parseStatement();
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 2540, in parseStatement
    return self.parseExpressionStatement(node);
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 2136, in parseExpressionStatement
    expr = self.parseExpression();
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1955, in parseExpression
    expr = self.isolateCoverGrammar(self.parseAssignmentExpression)
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1131, in isolateCoverGrammar
    result = parser()
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1923, in parseAssignmentExpression
    expr = self.parseConditionalExpression();
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1824, in parseConditionalExpression
    expr = self.inheritCoverGrammar(self.parseBinaryExpression);
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1146, in inheritCoverGrammar
    result = parser()
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1773, in parseBinaryExpression
    left = self.inheritCoverGrammar(self.parseUnaryExpression);
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1146, in inheritCoverGrammar
    result = parser()
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1749, in parseUnaryExpression
    expr = self.parsePostfixExpression()
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1702, in parsePostfixExpression
    expr = self.inheritCoverGrammar(self.parseLeftHandSideExpressionAllowCall)
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1146, in inheritCoverGrammar
    result = parser()
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1638, in parseLeftHandSideExpressionAllowCall
    self.parseNewExpression if self.matchKeyword('new') else self.parsePrimaryExpression)
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1146, in inheritCoverGrammar
    result = parser()
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1529, in parsePrimaryExpression
    return self.inheritCoverGrammar(self.parseGroupExpression)
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1146, in inheritCoverGrammar
    result = parser()
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1508, in parseGroupExpression
    self.expect(')')
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1031, in expect
    self.throwUnexpectedToken(token)
  File "/usr/local/scripts/test/venv/lib/python3.6/site-packages/pyjsparser/parser.py", line 1020, in throwUnexpectedToken
    raise self.unexpectedTokenError(token, message)
js2py.internals.simplex.JsException: SyntaxError: Line 2: Unexpected token ;
```

**Comment by gaardiolor** [comment]
Fixed similar to cfscrape by changing line 104 
from: `js = re.sub(r"a\.value = (.+ \+ t\.length).+", r"\1", js)`
to: `js = re.sub(r"a\.value = (.+ \+ t\.length(\).toFixed\(10\))?).+", r"\1", js)`

**Comment by pavlodvornikov** [comment]
Hello @gaardiolor 

Thank you for your investigation. Would you mind to open pull request for this? I will update on pip then.
