### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by ResQNetM** [pavlodvornikov/aiocfscrape#17]
When i tried to fetch chatmanager.pro throws this error:
  

> Traceback (most recent call last):
  File "test.py", line 12, in <module>
    loop.run_until_complete(test_open_page('https://chatmanager.pro', loop=loop))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "test.py", line 6, in test_open_page
    async with session.get(url) as resp:
  File "/home/valery/.local/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/home/valery/.local/lib/python3.6/site-packages/aiocfscrape/__init__.py", line 36, in _request
    return await self.solve_cf_challenge(resp, **kwargs)
  File "/home/valery/.local/lib/python3.6/site-packages/aiocfscrape/__init__.py", line 88, in solve_cf_challenge
    params["jschl_answer"] = str(float(js2py.eval_js(js)) + len(domain))
  File "/home/valery/.local/lib/python3.6/site-packages/js2py/evaljs.py", line 113, in eval_js
    return e.eval(js)
  File "/home/valery/.local/lib/python3.6/site-packages/js2py/evaljs.py", line 182, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "/home/valery/.local/lib/python3.6/site-packages/js2py/evaljs.py", line 177, in execute
    exec(compiled, self._context)
  File "<EvalJS snippet>", line 4, in <module>
  File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
  File "/home/valery/.local/lib/python3.6/site-packages/js2py/base.py", line 899, in __call__
    return self.call(self.GlobalObject, args)
  File "/home/valery/.local/lib/python3.6/site-packages/js2py/base.py", line 1344, in call
    return Js(self.code(*args))
  File "/home/valery/.local/lib/python3.6/site-packages/js2py/host/jseval.py", line 16, in Eval
    py_code = translate_js(code.to_string().value, '')
  File "/home/valery/.local/lib/python3.6/site-packages/js2py/translators/translator.py", line 66, in translate_js
    parsed = parser.parse(js) # js to esprima syntax tree
  File "/home/valery/.local/lib/python3.6/site-packages/pyjsparser/parser.py", line 3008, in parse
    program = self.parseProgram()
  File "/home/valery/.local/lib/python3.6/site-packages/pyjsparser/parser.py", line 2974, in parseProgram
    body = self.parseScriptBody()
  File "/home/valery/.local/lib/python3.6/site-packages/pyjsparser/parser.py", line 2963, in parseScriptBody
    statement = self.parseStatementListItem()
  File "/home/valery/.local/lib/python3.6/site-packages/pyjsparser/parser.py", line 2110, in parseStatementListItem
    return self.parseStatement()
  File "/home/valery/.local/lib/python3.6/site-packages/pyjsparser/parser.py", line 2718, in parseStatement
    self.consumeSemicolon()
  File "/home/valery/.local/lib/python3.6/site-packages/pyjsparser/parser.py", line 1108, in consumeSemicolon
    self.lex()
  File "/home/valery/.local/lib/python3.6/site-packages/pyjsparser/parser.py", line 972, in lex
    self.lookahead = self.advance()
  File "/home/valery/.local/lib/python3.6/site-packages/pyjsparser/parser.py", line 928, in advance
    - 1] == '${')):
IndexError: list index out of range

**Comment by ResQNetM** [comment]
are project alive?

**Comment by pavlodvornikov** [comment]
I sometimes update the project. Probably not often enough. I'll check the issue
