### ISSUE TITLE
'URL' object has no attribute 'decode'

### ISSUE THREAD

**Issue by DarkPhilosophy** [pavlodvornikov/aiocfscrape#2]
Traceback (most recent call last):
    async with self.scraper.get(url, headers=headers) as r:
  File "C:\Users\alexa\Anaconda3\lib\site-packages\aiohttp\client.py", line 603, in __aenter__
    self._resp = yield from self._coro
  File "C:\Users\alexa\Anaconda3\lib\site-packages\aiocfscrape\__init__.py", line 39, in _request
  File "C:\Users\alexa\Anaconda3\lib\site-packages\aiocfscrape\__init__.py", line 59, in solve_cf_challeng
    domain = parsed_url.netloc
  File "C:\Users\alexa\Anaconda3\lib\urllib\parse.py", line 357, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "C:\Users\alexa\Anaconda3\lib\urllib\parse.py", line 115, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "C:\Users\alexa\Anaconda3\lib\urllib\parse.py", line 99, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "C:\Users\alexa\Anaconda3\lib\urllib\parse.py", line 99, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'URL' object has no attribute 'decode'

**Comment by ape364** [comment]
fixed with https://github.com/pavlodvornikov/aiocfscrape/pull/3
@pavlodvornikov can u update package on pypi?
thanks

**Comment by pavlodvornikov** [comment]
@ape364 done

By the way, xdmn is also owner of aiocfscrape package on PyPi.

**Comment by xdmn** [comment]
@pavlodvornikov My release script was already prepared when i saw your comment :laughing: 

@ape364 Thank you for your contribution!
